### PR TITLE
limited comment line; only click shows full comments

### PR DESCRIPTION
**Pull request by junjiewe**
#46  I added function on limited comment line and set on click listener on list view so that it can shows a popup dialog display the full comment. Additionally, click back or anywhere else to return. @zhenkangub

### CODE REVIEW

**Review by junjieChen0608 — COMMENTED** [review]
The code properly addressed the issue #46 . However, given the fact that we're having multiple feature branches under developement, we might not accept your pull request to avoid future integration hassle, we will reference your code properly in our code base if we adopted your code. Thanks for your contribution!

**Comment by junjieChen0608** [comment]
Pull request is rejected, and #46 is closed.

**Review by zhenkangub — COMMENTED** [review]
Great work, the code indeed fixed the issue #46, but the UI could be better designed. As previous discussed, for now we cannot accept this pull request to avoid integration hassle, but we will recognize your contribution, and will reference you if we utilized your code in our later development!

**Comment by zhenkangub** [comment]
Update: @junjiewe 

#46 We used a new way to fix this issue, which is limiting the of number of words when a reviewer write the review(comments). In this way, we prevented the bad situation to happen in the first place, so that we don't need to do any further modification why displaying the reviews(comments). Anyway, thanks for your efforts!

**Pull request closed without merging**
