### PR TITLE
Feature/retrive course data

### PR DESCRIPTION
**Pull request by junjieChen0608**
#23 
Implemented drawer base activity, added utility class package, and courseData to represent data pulled from Firebase database

### CODE REVIEW

**Review by binyuand — APPROVED** [review]
feature presented as expected and code compiled without error.

**Comment by chandx** [comment]
add: network connection check toast

**Comment by junjieChen0608** [comment]
Internet access checked @chandx

**Comment by chandx** [comment]
seems fine. logic works.
As far as I see, no exception

**Pull request merged**
